// Copyright 2026 Vlad-Dumitru Popescu
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// tb_crv_cov — functional-coverage testbench for the Stage 5 (RV64IMAFDC) core.
//
// Loads a program from +vmem=<path> (plain $readmemh format, 32-bit words,
// generated by objcopy -O verilog --verilog-data-width 4).
// Drives the AXI ports with a single-outstanding zero-latency memory model
// covering ROM (0x00000000..0x0000FFFF) and RAM (0x00010000..0x0001FFFF).
// Halt is detected at write address (addr & 0xC000_0000) == 0x4000_0000.
//
// Coverage is tracked via manual bit arrays (Verilator 5.046 does not support
// native covergroup syntax — COVERIGN). Bins are written to a text file at
// $finish via +covout=<path> (default: coverage.txt).
//
// Bin layout (~84 named bins across 8 coverage groups):
//   cg_instr_class  21 bins  — instruction opcode class
//   cg_alu_sign     16 bins  — ALU op × result sign (cross)
//   cg_branch        6 bins  — branch type
//   cg_mem          16 bins  — memory size × address alignment (cross)
//   cg_amo          11 bins  — AMO operation type
//   cg_fp_rm         6 bins  — FP rounding mode
//   cg_trap          6 bins  — trap mcause
//   cg_icache        2 bins  — I$ miss path exercise (Stage 5e)
//   cg_dcache        2 bins  — D$ miss path exercise (Stage 5f)

`timescale 1ns/1ps

module tb_crv_cov;
  import kronos_pkg::*;

  // -------------------------------------------------------------------------
  // Clock and reset
  // -------------------------------------------------------------------------
  logic clk   = 1'b0;
  logic rst_n = 1'b0;

  always #5 clk = ~clk;

  // -------------------------------------------------------------------------
  // Memory: 32 K words (128 KB) covering ROM + RAM regions.
  // Word address = byte_addr[16:2].  Max byte addr = 0x1_FFFF.
  // -------------------------------------------------------------------------
  localparam int unsigned MEM_WORDS = 32768; // 128 KB / 4 bytes

  logic [31:0] mem [MEM_WORDS];

  // Word-address helper — returns 32-bit word index of the low half of the
  // 64-bit beat (even-aligned).  addr[16:3] selects the 64-bit beat; *2 gives
  // the first 32-bit word of that beat.
  function automatic logic [14:0] wa(input logic [63:0] addr);
    return {addr[16:3], 1'b0};
  endfunction

  // -------------------------------------------------------------------------
  // DUT: kronos_top
  // -------------------------------------------------------------------------
  kronos_axi_req_t  instr_req, data_req;
  kronos_axi_resp_t instr_rsp, data_rsp;

  logic        retire_valid;
  logic [63:0] retire_pc;
  logic [31:0] retire_instr;
  logic        retire_rd_wen;
  logic [ 4:0] retire_rd;
  logic [63:0] retire_rd_wdata;
  logic        retire_fp_wen;
  logic [ 4:0] retire_fp_rd;
  logic [63:0] retire_fp_wdata;
  logic        retire_mem_wen;
  logic [63:0] retire_mem_addr;
  logic [63:0] retire_mem_wdata;
  logic [2:0]  retire_mem_funct3;
  logic        retire_csr_wen;
  logic [11:0] retire_csr_addr;
  logic [63:0] retire_csr_wdata;
  logic        retire_trap_taken;
  logic [31:0] retire_trap_cause;

  // irq_timer_i: asserted when the program writes to 0x80000000.
  logic irq_timer;

  kronos_top u_top (
    .clk_i               (clk),
    .rst_ni              (rst_n),
    .instr_axi_req_o     (instr_req),
    .instr_axi_rsp_i     (instr_rsp),
    .data_axi_req_o      (data_req),
    .data_axi_rsp_i      (data_rsp),
    .irq_timer_i         (irq_timer),
    .irq_fast_i          (15'd0),
    .irq_msi_i           (1'b0),
    .irq_mei_i           (1'b0),
    .irq_ssi_i           (1'b0),
    .irq_sti_i           (1'b0),
    .irq_sei_i           (1'b0),
    .boot_addr_i         (32'h0),
    .retire_valid_o      (retire_valid),
    .retire_pc_o         (retire_pc),
    .retire_instr_o      (retire_instr),
    .retire_rd_wen_o     (retire_rd_wen),
    .retire_rd_o         (retire_rd),
    .retire_rd_wdata_o   (retire_rd_wdata),
    .retire_fp_wen_o     (retire_fp_wen),
    .retire_fp_rd_o      (retire_fp_rd),
    .retire_fp_wdata_o   (retire_fp_wdata),
    .retire_mem_wen_o    (retire_mem_wen),
    .retire_mem_addr_o   (retire_mem_addr),
    .retire_mem_wdata_o  (retire_mem_wdata),
    .retire_mem_funct3_o (retire_mem_funct3),
    .retire_csr_wen_o    (retire_csr_wen),
    .retire_csr_addr_o   (retire_csr_addr),
    .retire_csr_wdata_o  (retire_csr_wdata),
    .retire_trap_taken_o (retire_trap_taken),
    .retire_trap_cause_o (retire_trap_cause)
  );

  // -------------------------------------------------------------------------
  // Decoded retire-instruction fields
  // -------------------------------------------------------------------------
  logic [6:0] opcode;
  logic [2:0] funct3;
  logic [6:0] funct7;
  logic [2:0] rm;

  assign opcode = retire_instr[6:0];
  assign funct3 = retire_instr[14:12];
  assign funct7 = retire_instr[31:25];
  assign rm     = retire_instr[14:12];  // FP rounding mode field = funct3

  // -------------------------------------------------------------------------
  // AXI instruction port — multi-beat burst support (INCR and WRAP)
  //
  // The icache issues WRAP8 burst refills (ar.len=7, ar.burst=2'b10, 64-bit
  // beats).  This model captures the AR handshake, then drives successive
  // R beats advancing the address per AXI WRAP or INCR rules, asserting
  // r.last on the final beat.
  // -------------------------------------------------------------------------
  logic        instr_r_pend;
  logic [63:0] instr_r_data_q;
  logic        instr_r_last_q;
  logic [63:0] instr_ar_addr_q;   // captured AR address
  logic [ 7:0] instr_ar_len_q;    // captured AR len (beats-1)
  logic [ 1:0] instr_ar_burst_q;  // captured AR burst type
  logic [ 7:0] instr_beat_q;      // current beat index (0..len)

  // TB beat-tracking helpers (promoted from `automatic` block-locals; see R2).
  logic [63:0] instr_beat0_addr;
  logic [ 7:0] instr_next_beat;
  logic [63:0] instr_next_addr;

  // Beat-address helper: returns byte address for beat b of a WRAP/INCR burst.
  function automatic logic [63:0] burst_addr(
    input logic [63:0] base,
    input logic [ 7:0] burst_len,  // ar_len
    input logic [ 1:0] burst_type, // 01=INCR 10=WRAP
    input logic [ 7:0] beat
  );
    logic [63:0] off;
    logic [63:0] line_mask;
    off = {53'h0, beat, 3'h0};  // beat * 8 bytes (64-bit beats)
    if (burst_type == 2'b10) begin
      // WRAP: mask = ((len+1)*8 - 1), for len=7 → 0x3F
      line_mask = (64'(burst_len) + 64'd1) * 64'd8 - 64'd1;
      return (base & ~line_mask) | ((base + off) & line_mask);
    end else begin
      // INCR
      return base + off;
    end
  endfunction

  always_comb begin
    instr_rsp          = '0;
    instr_rsp.ar_ready = !instr_r_pend;
    instr_rsp.r_valid  = instr_r_pend;
    instr_rsp.r.data   = instr_r_data_q;
    instr_rsp.r.last   = instr_r_last_q;
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      instr_r_pend      <= 1'b0;
      instr_r_data_q    <= '0;
      instr_r_last_q    <= 1'b0;
      instr_ar_addr_q   <= '0;
      instr_ar_len_q    <= '0;
      instr_ar_burst_q  <= '0;
      instr_beat_q      <= '0;
    end else begin
      if (!instr_r_pend && instr_req.ar_valid) begin
        // Capture AR and prepare first beat
        instr_ar_addr_q  <= instr_req.ar.addr;
        instr_ar_len_q   <= instr_req.ar.len;
        instr_ar_burst_q <= instr_req.ar.burst;
        instr_beat_q     <= 8'd0;
        instr_beat0_addr  = burst_addr(instr_req.ar.addr, instr_req.ar.len,
                                       instr_req.ar.burst, 8'd0);
        instr_r_data_q <= {mem[wa(instr_beat0_addr)+1], mem[wa(instr_beat0_addr)]};
        instr_r_last_q <= (instr_req.ar.len == 8'd0);
        instr_r_pend   <= 1'b1;
      end else if (instr_r_pend && instr_req.r_ready) begin
        if (instr_beat_q == instr_ar_len_q) begin
          // Last beat consumed — retire burst
          instr_r_pend  <= 1'b0;
          instr_beat_q  <= 8'd0;
        end else begin
          // Advance to next beat
          instr_next_beat = instr_beat_q + 8'd1;
          instr_next_addr = burst_addr(instr_ar_addr_q, instr_ar_len_q,
                                       instr_ar_burst_q, instr_next_beat);
          instr_beat_q   <= instr_next_beat;
          instr_r_data_q <= {mem[wa(instr_next_addr)+1], mem[wa(instr_next_addr)]};
          instr_r_last_q <= (instr_next_beat == instr_ar_len_q);
        end
      end
    end
  end

  // -------------------------------------------------------------------------
  // AXI data port — multi-beat read + write (dcache issues 8-beat WRAP/INCR)
  // Halt is detected via retire_mem_wen (store to 0x4000_0000 sentinel).
  // -------------------------------------------------------------------------
  // Read channel
  logic        data_r_pend;
  logic [63:0] data_ar_addr_q;
  logic [ 7:0] data_ar_len_q;
  logic [ 1:0] data_ar_burst_q;
  logic [ 7:0] data_r_beat;
  logic [63:0] data_r_data_q;
  // TB beat-tracking helpers (promoted from `automatic` block-locals; see R2).
  logic [ 7:0] data_nb;
  logic [63:0] data_na;
  logic [63:0] data_waddr;
  int          data_wi_lo;
  int          data_wi_hi;
  // Mem-coverage helpers (promoted from `automatic` block-locals; see R2).
  logic [1:0]  cov_msize;
  logic [2:0]  cov_maddr3;
  int          cov_align_bucket;
  // Write channel
  logic        data_aw_pend;
  logic [63:0] data_aw_addr_q;
  logic [ 7:0] data_aw_len_q;
  logic [ 7:0] data_w_beat;
  logic        data_b_pend;
  logic [31:0] halted;
  int          irq_countdown;  // cycles remaining for irq_timer assertion

  always_comb begin
    data_rsp          = '0;
    data_rsp.ar_ready = ~data_r_pend;
    data_rsp.aw_ready = ~data_aw_pend;
    data_rsp.w_ready  = data_aw_pend;
    data_rsp.r_valid  = data_r_pend;
    data_rsp.r.data   = data_r_data_q;
    data_rsp.r.last   = (data_r_beat == data_ar_len_q);
    data_rsp.b_valid  = data_b_pend;
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      data_r_pend    <= 1'b0;
      data_ar_addr_q <= '0;
      data_ar_len_q  <= '0;
      data_ar_burst_q <= '0;
      data_r_beat    <= '0;
      data_r_data_q  <= '0;
      data_aw_pend   <= 1'b0;
      data_aw_addr_q <= '0;
      data_aw_len_q  <= '0;
      data_w_beat    <= '0;
      data_b_pend    <= 1'b0;
    end else begin
      // AR handshake
      if (!data_r_pend && data_req.ar_valid) begin
        data_ar_addr_q  <= data_req.ar.addr;
        data_ar_len_q   <= data_req.ar.len;
        data_ar_burst_q <= data_req.ar.burst;
        data_r_beat     <= 8'd0;
        data_r_data_q   <= {mem[wa(burst_addr(data_req.ar.addr, data_req.ar.len,
                                              data_req.ar.burst, 8'd0)) + 1],
                             mem[wa(burst_addr(data_req.ar.addr, data_req.ar.len,
                                              data_req.ar.burst, 8'd0))]};
        data_r_pend     <= 1'b1;
      end else if (data_r_pend && data_req.r_ready) begin
        if (data_r_beat == data_ar_len_q) begin
          data_r_pend <= 1'b0;
          data_r_beat <= 8'd0;
        end else begin
          data_nb       = data_r_beat + 8'd1;
          data_na       = burst_addr(data_ar_addr_q, data_ar_len_q,
                                     data_ar_burst_q, data_nb);
          data_r_beat   <= data_nb;
          data_r_data_q <= {mem[wa(data_na)+1], mem[wa(data_na)]};
        end
      end

      // AW handshake
      if (!data_aw_pend && data_req.aw_valid) begin
        data_aw_addr_q <= data_req.aw.addr;
        data_aw_len_q  <= data_req.aw.len;
        data_w_beat    <= 8'd0;
        data_aw_pend   <= 1'b1;
      end

      // W channel write beats
      if (data_aw_pend && data_req.w_valid) begin
        data_waddr = data_aw_addr_q + {56'b0, data_w_beat} * 8;
        data_wi_lo = int'({data_waddr[16:3], 1'b0});
        data_wi_hi = data_wi_lo + 1;
        if ((data_waddr & 64'hC000_0000) != 64'h4000_0000) begin
          if (data_req.w.strb[0]) mem[data_wi_lo][ 7: 0] <= data_req.w.data[ 7: 0];
          if (data_req.w.strb[1]) mem[data_wi_lo][15: 8] <= data_req.w.data[15: 8];
          if (data_req.w.strb[2]) mem[data_wi_lo][23:16] <= data_req.w.data[23:16];
          if (data_req.w.strb[3]) mem[data_wi_lo][31:24] <= data_req.w.data[31:24];
          if (data_req.w.strb[4]) mem[data_wi_hi][ 7: 0] <= data_req.w.data[39:32];
          if (data_req.w.strb[5]) mem[data_wi_hi][15: 8] <= data_req.w.data[47:40];
          if (data_req.w.strb[6]) mem[data_wi_hi][23:16] <= data_req.w.data[55:48];
          if (data_req.w.strb[7]) mem[data_wi_hi][31:24] <= data_req.w.data[63:56];
        end
        data_w_beat <= data_w_beat + 8'd1;
        if (data_req.w.last) begin
          data_aw_pend <= 1'b0;
          data_b_pend  <= 1'b1;
        end
      end

      // B handshake
      if (data_b_pend && data_req.b_ready) begin
        data_b_pend <= 1'b0;
      end
    end
  end

  // -------------------------------------------------------------------------
  // IRQ trigger: store to 0x80000000 from retire port (write-back D$ may
  // never write the magic address through to AXI, so we watch retire).
  // -------------------------------------------------------------------------
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      irq_countdown <= 0;
    end else if (retire_mem_wen && retire_mem_addr == 64'h8000_0000) begin
      irq_countdown <= 16;
    end else if (irq_countdown > 0) begin
      irq_countdown <= irq_countdown - 1;
    end
  end

  // -------------------------------------------------------------------------
  // Halt detection via retire port (store to 0x4000_0000 sentinel).
  // Works with write-back dcache (halt store may never trigger AXI writeback).
  // -------------------------------------------------------------------------
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n)
      halted <= '0;
    else if (retire_mem_wen && (retire_mem_addr & 64'hC000_0000) == 64'h4000_0000)
      halted <= halted + 32'd1;
  end

  assign irq_timer = (irq_countdown > 0);

  // =========================================================================
  // Functional coverage — manual bit arrays (Verilator 5.046 COVERIGN)
  // =========================================================================

  // -------------------------------------------------------------------------
  // cg_instr_class (21 bins) — instruction opcode
  // -------------------------------------------------------------------------
  bit cov_op_lui;
  bit cov_op_auipc;
  bit cov_op_jal;
  bit cov_op_jalr;
  bit cov_op_branch;
  bit cov_op_load;
  bit cov_op_store;
  bit cov_op_imm;
  bit cov_op_reg;
  bit cov_op_imm32;
  bit cov_op_reg32;
  bit cov_op_fence;
  bit cov_op_system;
  bit cov_op_amo;
  bit cov_op_load_fp;
  bit cov_op_store_fp;
  bit cov_op_fmadd;
  bit cov_op_fmsub;
  bit cov_op_fnmsub;
  bit cov_op_fnmadd;
  bit cov_op_fp;

  // -------------------------------------------------------------------------
  // cg_alu_sign (16 bins) — ALU op × result sign cross
  // -------------------------------------------------------------------------
  // 8 funct3 bins × 2 sign bins = 16
  bit cov_alu_add_sub_pos;   bit cov_alu_add_sub_neg;
  bit cov_alu_sll_pos;       bit cov_alu_sll_neg;
  bit cov_alu_slt_pos;       bit cov_alu_slt_neg;
  bit cov_alu_sltu_pos;      bit cov_alu_sltu_neg;
  bit cov_alu_xor_pos;       bit cov_alu_xor_neg;
  bit cov_alu_srl_sra_pos;   bit cov_alu_srl_sra_neg;
  bit cov_alu_or_pos;        bit cov_alu_or_neg;
  bit cov_alu_and_pos;       bit cov_alu_and_neg;

  // -------------------------------------------------------------------------
  // cg_branch (6 bins) — branch type
  // -------------------------------------------------------------------------
  bit cov_br_beq;
  bit cov_br_bne;
  bit cov_br_blt;
  bit cov_br_bge;
  bit cov_br_bltu;
  bit cov_br_bgeu;

  // -------------------------------------------------------------------------
  // cg_mem (16 bins) — size × alignment cross
  // -------------------------------------------------------------------------
  // 4 size bins × 4 align bins = 16
  bit cov_mem_byte_aligned;    bit cov_mem_byte_off4;
  bit cov_mem_byte_off2;       bit cov_mem_byte_odd;
  bit cov_mem_half_aligned;    bit cov_mem_half_off4;
  bit cov_mem_half_off2;       bit cov_mem_half_odd;
  bit cov_mem_word_aligned;    bit cov_mem_word_off4;
  bit cov_mem_word_off2;       bit cov_mem_word_odd;
  bit cov_mem_double_aligned;  bit cov_mem_double_off4;
  bit cov_mem_double_off2;     bit cov_mem_double_odd;

  // -------------------------------------------------------------------------
  // cg_amo (11 bins) — AMO type
  // -------------------------------------------------------------------------
  bit cov_amo_lr;
  bit cov_amo_sc;
  bit cov_amo_swap;
  bit cov_amo_add;
  bit cov_amo_xor;
  bit cov_amo_and;
  bit cov_amo_or;
  bit cov_amo_min;
  bit cov_amo_max;
  bit cov_amo_minu;
  bit cov_amo_maxu;

  // -------------------------------------------------------------------------
  // cg_fp_rm (6 bins) — FP rounding mode
  // -------------------------------------------------------------------------
  bit cov_rm_rne;
  bit cov_rm_rtz;
  bit cov_rm_rdn;
  bit cov_rm_rup;
  bit cov_rm_rmm;
  bit cov_rm_dyn;

  // -------------------------------------------------------------------------
  // cg_trap (6 bins) — trap mcause via CSR write to mcause (0x342)
  // -------------------------------------------------------------------------
  bit cov_trap_illegal;
  bit cov_trap_ecall_m;
  bit cov_trap_ebreak;
  bit cov_trap_ld_misalign;
  bit cov_trap_st_misalign;
  bit cov_trap_irq_timer;

  // -------------------------------------------------------------------------
  // cg_icache (2 bins) — Stage 5e I-cache miss path exercise
  // Tracks whether the I$ miss event (miss_pulse_o from kronos_icache,
  // mapped to event_bus[16] via icache_miss_pulse in kronos_top) was ever
  // asserted and whether at least one hit cycle was observed.
  // -------------------------------------------------------------------------
  bit cov_icache_miss_seen;    // at least one I$ miss occurred
  bit cov_icache_no_miss_seen; // at least one cycle with no miss (normal fetch)

  // -------------------------------------------------------------------------
  // cg_dcache (2 bins) — Stage 5f D-cache miss path exercise (Stage 5f)
  // Tracks whether the D$ miss event (miss_pulse_o from kronos_dcache,
  // mapped to event_bus[17] via dcache_miss_pulse in kronos_top) was ever
  // asserted and whether at least one hit cycle was observed.
  // -------------------------------------------------------------------------
  bit cov_dcache_miss_seen;    // at least one D$ miss occurred
  bit cov_dcache_no_miss_seen; // at least one D$ hit (no miss)

  // -------------------------------------------------------------------------
  // Sampling logic — combinational helpers
  // -------------------------------------------------------------------------
  logic is_alu_op;
  logic is_branch;
  logic is_mem_op;
  logic is_amo;
  logic is_fp_op;

  assign is_alu_op = retire_valid &&
                     (opcode == 7'b0110011 || opcode == 7'b0010011 ||
                      opcode == 7'b0111011 || opcode == 7'b0011011);
  assign is_branch = retire_valid && (opcode == 7'b1100011);
  assign is_mem_op = retire_valid &&
                     (opcode == 7'b0000011 || opcode == 7'b0100011);
  assign is_amo    = retire_valid && (opcode == 7'b0101111);
  assign is_fp_op  = retire_valid &&
                     (opcode == 7'b1010011 || opcode == 7'b1000011 ||
                      opcode == 7'b1000111 || opcode == 7'b1001011 ||
                      opcode == 7'b1001111);

  // -------------------------------------------------------------------------
  // Sample on every posedge clk (not gated by retire_valid here — the
  // individual always_ff blocks gate internally via if statements).
  // -------------------------------------------------------------------------

  // -- cg_instr_class --------------------------------------------------------
  always_ff @(posedge clk) begin
    if (retire_valid) begin
      unique case (opcode)
        7'b0110111: cov_op_lui      <= 1'b1;
        7'b0010111: cov_op_auipc    <= 1'b1;
        7'b1101111: cov_op_jal      <= 1'b1;
        7'b1100111: cov_op_jalr     <= 1'b1;
        7'b1100011: cov_op_branch   <= 1'b1;
        7'b0000011: cov_op_load     <= 1'b1;
        7'b0100011: cov_op_store    <= 1'b1;
        7'b0010011: cov_op_imm      <= 1'b1;
        7'b0110011: cov_op_reg      <= 1'b1;
        7'b0011011: cov_op_imm32    <= 1'b1;
        7'b0111011: cov_op_reg32    <= 1'b1;
        7'b0001111: cov_op_fence    <= 1'b1;
        7'b1110011: cov_op_system   <= 1'b1;
        7'b0101111: cov_op_amo      <= 1'b1;
        7'b0000111: cov_op_load_fp  <= 1'b1;
        7'b0100111: cov_op_store_fp <= 1'b1;
        7'b1000011: cov_op_fmadd    <= 1'b1;
        7'b1000111: cov_op_fmsub    <= 1'b1;
        7'b1001011: cov_op_fnmsub   <= 1'b1;
        7'b1001111: cov_op_fnmadd   <= 1'b1;
        7'b1010011: cov_op_fp       <= 1'b1;
        default: ;
      endcase
    end
  end

  // -- cg_alu_sign -----------------------------------------------------------
  always_ff @(posedge clk) begin
    if (is_alu_op) begin
      unique case (funct3)
        3'b000: begin
          if (!retire_rd_wdata[63]) cov_alu_add_sub_pos <= 1'b1;
          else                      cov_alu_add_sub_neg <= 1'b1;
        end
        3'b001: begin
          if (!retire_rd_wdata[63]) cov_alu_sll_pos <= 1'b1;
          else                      cov_alu_sll_neg <= 1'b1;
        end
        3'b010: begin
          if (!retire_rd_wdata[63]) cov_alu_slt_pos <= 1'b1;
          else                      cov_alu_slt_neg <= 1'b1;
        end
        3'b011: begin
          if (!retire_rd_wdata[63]) cov_alu_sltu_pos <= 1'b1;
          else                      cov_alu_sltu_neg <= 1'b1;
        end
        3'b100: begin
          if (!retire_rd_wdata[63]) cov_alu_xor_pos <= 1'b1;
          else                      cov_alu_xor_neg <= 1'b1;
        end
        3'b101: begin
          if (!retire_rd_wdata[63]) cov_alu_srl_sra_pos <= 1'b1;
          else                      cov_alu_srl_sra_neg <= 1'b1;
        end
        3'b110: begin
          if (!retire_rd_wdata[63]) cov_alu_or_pos <= 1'b1;
          else                      cov_alu_or_neg <= 1'b1;
        end
        3'b111: begin
          if (!retire_rd_wdata[63]) cov_alu_and_pos <= 1'b1;
          else                      cov_alu_and_neg <= 1'b1;
        end
        default: ;
      endcase
    end
  end

  // -- cg_branch -------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (is_branch) begin
      unique case (funct3)
        3'b000: cov_br_beq  <= 1'b1;
        3'b001: cov_br_bne  <= 1'b1;
        3'b100: cov_br_blt  <= 1'b1;
        3'b101: cov_br_bge  <= 1'b1;
        3'b110: cov_br_bltu <= 1'b1;
        3'b111: cov_br_bgeu <= 1'b1;
        default: ;
      endcase
    end
  end

  // -- cg_mem ----------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (is_mem_op) begin
      // size = funct3[1:0], align bucket = retire_mem_addr[2:0]
      cov_msize  = funct3[1:0];
      cov_maddr3 = retire_mem_addr[2:0];
      if      (cov_maddr3 == 3'b000)                                       cov_align_bucket = 0;
      else if (cov_maddr3 == 3'b100)                                       cov_align_bucket = 1;
      else if (cov_maddr3 == 3'b010 || cov_maddr3 == 3'b110)               cov_align_bucket = 2;
      else                                                                  cov_align_bucket = 3;

      unique case ({cov_msize, 2'(cov_align_bucket)})
        4'b0000: cov_mem_byte_aligned   <= 1'b1;
        4'b0001: cov_mem_byte_off4      <= 1'b1;
        4'b0010: cov_mem_byte_off2      <= 1'b1;
        4'b0011: cov_mem_byte_odd       <= 1'b1;
        4'b0100: cov_mem_half_aligned   <= 1'b1;
        4'b0101: cov_mem_half_off4      <= 1'b1;
        4'b0110: cov_mem_half_off2      <= 1'b1;
        4'b0111: cov_mem_half_odd       <= 1'b1;
        4'b1000: cov_mem_word_aligned   <= 1'b1;
        4'b1001: cov_mem_word_off4      <= 1'b1;
        4'b1010: cov_mem_word_off2      <= 1'b1;
        4'b1011: cov_mem_word_odd       <= 1'b1;
        4'b1100: cov_mem_double_aligned <= 1'b1;
        4'b1101: cov_mem_double_off4    <= 1'b1;
        4'b1110: cov_mem_double_off2    <= 1'b1;
        4'b1111: cov_mem_double_odd     <= 1'b1;
        default: ;
      endcase
    end
  end

  // -- cg_amo ----------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (is_amo) begin
      unique case (funct7[6:2])
        5'b00010: cov_amo_lr   <= 1'b1;
        5'b00011: cov_amo_sc   <= 1'b1;
        5'b00001: cov_amo_swap <= 1'b1;
        5'b00000: cov_amo_add  <= 1'b1;
        5'b00100: cov_amo_xor  <= 1'b1;
        5'b01100: cov_amo_and  <= 1'b1;
        5'b01000: cov_amo_or   <= 1'b1;
        5'b10000: cov_amo_min  <= 1'b1;
        5'b10100: cov_amo_max  <= 1'b1;
        5'b11000: cov_amo_minu <= 1'b1;
        5'b11100: cov_amo_maxu <= 1'b1;
        default: ;
      endcase
    end
  end

  // -- cg_fp_rm --------------------------------------------------------------
  always_ff @(posedge clk) begin
    if (is_fp_op) begin
      unique case (rm)
        3'b000: cov_rm_rne <= 1'b1;
        3'b001: cov_rm_rtz <= 1'b1;
        3'b010: cov_rm_rdn <= 1'b1;
        3'b011: cov_rm_rup <= 1'b1;
        3'b100: cov_rm_rmm <= 1'b1;
        3'b111: cov_rm_dyn <= 1'b1;
        default: ;
      endcase
    end
  end

  // -- cg_trap ---------------------------------------------------------------
  // Use retire_trap_taken_o / retire_trap_cause_o (new debug ports on kronos_top)
  // instead of watching explicit CSR writes to mcause (0x342).  Hardware traps
  // write mcause internally; they never appear in the retire CSR-write stream.
  always_ff @(posedge clk) begin
    if (retire_trap_taken) begin
      unique case (retire_trap_cause)
        32'd2:             cov_trap_illegal     <= 1'b1;
        32'd11:            cov_trap_ecall_m     <= 1'b1;
        32'd3:             cov_trap_ebreak      <= 1'b1;
        32'd4:             cov_trap_ld_misalign <= 1'b1;
        32'd6:             cov_trap_st_misalign <= 1'b1;
        32'h8000_0007:     cov_trap_irq_timer   <= 1'b1;
        default: ;
      endcase
    end
  end

  // -- cg_icache -------------------------------------------------------------
  // Hierarchical reference to the icache_miss_pulse signal in kronos_top.
  // This is a registered 1-cycle pulse raised on every I$ miss.
  always_ff @(posedge clk) begin
    if (u_top.icache_miss_pulse) cov_icache_miss_seen    <= 1'b1;
    else                         cov_icache_no_miss_seen <= 1'b1;
  end

  // -- cg_dcache (Stage 5f) --------------------------------------------------
  // Hierarchical reference to the dcache_miss_pulse signal in kronos_top.
  always_ff @(posedge clk) begin
    if (u_top.dcache_miss_pulse) cov_dcache_miss_seen    <= 1'b1;
    else                         cov_dcache_no_miss_seen <= 1'b1;
  end

  // =========================================================================
  // Coverage dump at $finish
  // =========================================================================
  // Writes a text file: one line per bin, "group.bin <0|1>"
  task automatic dump_coverage(string filename);
    int fd;
    fd = $fopen(filename, "w");
    if (fd == 0) begin
      $display("tb_crv_cov: WARNING — cannot open coverage file %s", filename);
      return;
    end
    // cg_instr_class
    $fwrite(fd, "cg_instr_class.op_lui       %0d\n", cov_op_lui);
    $fwrite(fd, "cg_instr_class.op_auipc     %0d\n", cov_op_auipc);
    $fwrite(fd, "cg_instr_class.op_jal       %0d\n", cov_op_jal);
    $fwrite(fd, "cg_instr_class.op_jalr      %0d\n", cov_op_jalr);
    $fwrite(fd, "cg_instr_class.op_branch    %0d\n", cov_op_branch);
    $fwrite(fd, "cg_instr_class.op_load      %0d\n", cov_op_load);
    $fwrite(fd, "cg_instr_class.op_store     %0d\n", cov_op_store);
    $fwrite(fd, "cg_instr_class.op_imm       %0d\n", cov_op_imm);
    $fwrite(fd, "cg_instr_class.op_reg       %0d\n", cov_op_reg);
    $fwrite(fd, "cg_instr_class.op_imm32     %0d\n", cov_op_imm32);
    $fwrite(fd, "cg_instr_class.op_reg32     %0d\n", cov_op_reg32);
    $fwrite(fd, "cg_instr_class.op_fence     %0d\n", cov_op_fence);
    $fwrite(fd, "cg_instr_class.op_system    %0d\n", cov_op_system);
    $fwrite(fd, "cg_instr_class.op_amo       %0d\n", cov_op_amo);
    $fwrite(fd, "cg_instr_class.op_load_fp   %0d\n", cov_op_load_fp);
    $fwrite(fd, "cg_instr_class.op_store_fp  %0d\n", cov_op_store_fp);
    $fwrite(fd, "cg_instr_class.op_fmadd     %0d\n", cov_op_fmadd);
    $fwrite(fd, "cg_instr_class.op_fmsub     %0d\n", cov_op_fmsub);
    $fwrite(fd, "cg_instr_class.op_fnmsub    %0d\n", cov_op_fnmsub);
    $fwrite(fd, "cg_instr_class.op_fnmadd    %0d\n", cov_op_fnmadd);
    $fwrite(fd, "cg_instr_class.op_fp        %0d\n", cov_op_fp);
    // cg_alu_sign
    $fwrite(fd, "cg_alu_sign.add_sub_pos     %0d\n", cov_alu_add_sub_pos);
    $fwrite(fd, "cg_alu_sign.add_sub_neg     %0d\n", cov_alu_add_sub_neg);
    $fwrite(fd, "cg_alu_sign.sll_pos         %0d\n", cov_alu_sll_pos);
    $fwrite(fd, "cg_alu_sign.sll_neg         %0d\n", cov_alu_sll_neg);
    $fwrite(fd, "cg_alu_sign.slt_pos         %0d\n", cov_alu_slt_pos);
    $fwrite(fd, "cg_alu_sign.slt_neg         %0d\n", cov_alu_slt_neg);
    $fwrite(fd, "cg_alu_sign.sltu_pos        %0d\n", cov_alu_sltu_pos);
    $fwrite(fd, "cg_alu_sign.sltu_neg        %0d\n", cov_alu_sltu_neg);
    $fwrite(fd, "cg_alu_sign.xor_pos         %0d\n", cov_alu_xor_pos);
    $fwrite(fd, "cg_alu_sign.xor_neg         %0d\n", cov_alu_xor_neg);
    $fwrite(fd, "cg_alu_sign.srl_sra_pos     %0d\n", cov_alu_srl_sra_pos);
    $fwrite(fd, "cg_alu_sign.srl_sra_neg     %0d\n", cov_alu_srl_sra_neg);
    $fwrite(fd, "cg_alu_sign.or_pos          %0d\n", cov_alu_or_pos);
    $fwrite(fd, "cg_alu_sign.or_neg          %0d\n", cov_alu_or_neg);
    $fwrite(fd, "cg_alu_sign.and_pos         %0d\n", cov_alu_and_pos);
    $fwrite(fd, "cg_alu_sign.and_neg         %0d\n", cov_alu_and_neg);
    // cg_branch
    $fwrite(fd, "cg_branch.beq               %0d\n", cov_br_beq);
    $fwrite(fd, "cg_branch.bne               %0d\n", cov_br_bne);
    $fwrite(fd, "cg_branch.blt               %0d\n", cov_br_blt);
    $fwrite(fd, "cg_branch.bge               %0d\n", cov_br_bge);
    $fwrite(fd, "cg_branch.bltu              %0d\n", cov_br_bltu);
    $fwrite(fd, "cg_branch.bgeu              %0d\n", cov_br_bgeu);
    // cg_mem
    $fwrite(fd, "cg_mem.byte_aligned         %0d\n", cov_mem_byte_aligned);
    $fwrite(fd, "cg_mem.byte_off4            %0d\n", cov_mem_byte_off4);
    $fwrite(fd, "cg_mem.byte_off2            %0d\n", cov_mem_byte_off2);
    $fwrite(fd, "cg_mem.byte_odd             %0d\n", cov_mem_byte_odd);
    $fwrite(fd, "cg_mem.half_aligned         %0d\n", cov_mem_half_aligned);
    $fwrite(fd, "cg_mem.half_off4            %0d\n", cov_mem_half_off4);
    $fwrite(fd, "cg_mem.half_off2            %0d\n", cov_mem_half_off2);
    $fwrite(fd, "cg_mem.half_odd             %0d\n", cov_mem_half_odd);
    $fwrite(fd, "cg_mem.word_aligned         %0d\n", cov_mem_word_aligned);
    $fwrite(fd, "cg_mem.word_off4            %0d\n", cov_mem_word_off4);
    $fwrite(fd, "cg_mem.word_off2            %0d\n", cov_mem_word_off2);
    $fwrite(fd, "cg_mem.word_odd             %0d\n", cov_mem_word_odd);
    $fwrite(fd, "cg_mem.double_aligned       %0d\n", cov_mem_double_aligned);
    $fwrite(fd, "cg_mem.double_off4          %0d\n", cov_mem_double_off4);
    $fwrite(fd, "cg_mem.double_off2          %0d\n", cov_mem_double_off2);
    $fwrite(fd, "cg_mem.double_odd           %0d\n", cov_mem_double_odd);
    // cg_amo
    $fwrite(fd, "cg_amo.lr                   %0d\n", cov_amo_lr);
    $fwrite(fd, "cg_amo.sc                   %0d\n", cov_amo_sc);
    $fwrite(fd, "cg_amo.amoswap              %0d\n", cov_amo_swap);
    $fwrite(fd, "cg_amo.amoadd               %0d\n", cov_amo_add);
    $fwrite(fd, "cg_amo.amoxor               %0d\n", cov_amo_xor);
    $fwrite(fd, "cg_amo.amoand               %0d\n", cov_amo_and);
    $fwrite(fd, "cg_amo.amoor                %0d\n", cov_amo_or);
    $fwrite(fd, "cg_amo.amomin               %0d\n", cov_amo_min);
    $fwrite(fd, "cg_amo.amomax               %0d\n", cov_amo_max);
    $fwrite(fd, "cg_amo.amominu              %0d\n", cov_amo_minu);
    $fwrite(fd, "cg_amo.amomaxu              %0d\n", cov_amo_maxu);
    // cg_fp_rm
    $fwrite(fd, "cg_fp_rm.rne                %0d\n", cov_rm_rne);
    $fwrite(fd, "cg_fp_rm.rtz                %0d\n", cov_rm_rtz);
    $fwrite(fd, "cg_fp_rm.rdn                %0d\n", cov_rm_rdn);
    $fwrite(fd, "cg_fp_rm.rup                %0d\n", cov_rm_rup);
    $fwrite(fd, "cg_fp_rm.rmm                %0d\n", cov_rm_rmm);
    $fwrite(fd, "cg_fp_rm.dyn                %0d\n", cov_rm_dyn);
    // cg_trap
    $fwrite(fd, "cg_trap.illegal             %0d\n", cov_trap_illegal);
    $fwrite(fd, "cg_trap.ecall_m             %0d\n", cov_trap_ecall_m);
    $fwrite(fd, "cg_trap.ebreak              %0d\n", cov_trap_ebreak);
    $fwrite(fd, "cg_trap.ld_misalign         %0d\n", cov_trap_ld_misalign);
    $fwrite(fd, "cg_trap.st_misalign         %0d\n", cov_trap_st_misalign);
    $fwrite(fd, "cg_trap.irq_timer           %0d\n", cov_trap_irq_timer);
    // cg_icache
    $fwrite(fd, "cg_icache.miss_seen         %0d\n", cov_icache_miss_seen);
    $fwrite(fd, "cg_icache.no_miss_seen      %0d\n", cov_icache_no_miss_seen);
    // cg_dcache (Stage 5f)
    $fwrite(fd, "cg_dcache.miss_seen         %0d\n", cov_dcache_miss_seen);
    $fwrite(fd, "cg_dcache.no_miss_seen      %0d\n", cov_dcache_no_miss_seen);
    $fclose(fd);
  endtask

  // =========================================================================
  // Test driver
  // =========================================================================
  int          cycle_count;
  string       vmem_path;
  string       covout_path;

  initial begin
    // Required: +vmem=<path>
    if (!$value$plusargs("vmem=%s", vmem_path)) begin
      $fatal(1, "tb_crv_cov: +vmem=<path> required");
    end
    // Optional: +covout=<path> (default: coverage.txt)
    if (!$value$plusargs("covout=%s", covout_path)) begin
      covout_path = "coverage.txt";
    end

    // Load program into memory
    $readmemh(vmem_path, mem);

    // Reset sequence
    cycle_count = 0;
    rst_n = 1'b0;
    repeat (8) @(posedge clk);
    @(negedge clk); rst_n = 1'b1;

    // Run until halt or cycle cap (1 000 000 cycles)
    fork
      begin : wait_halt
        wait (halted > 0);
        // Drain a few cycles for trailing retirements
        repeat (20) @(posedge clk);
      end
      begin : cap
        repeat (1_000_000) @(posedge clk);
        $display("tb_crv_cov: cycle cap reached (no halt in 1M cycles)");
      end
    join_any
    disable fork;

    dump_coverage(covout_path);
    $display("tb_crv_cov: coverage written to %s", covout_path);
    $finish;
  end

  // Cycle counter (informational)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) cycle_count <= 0;
    else        cycle_count <= cycle_count + 1;
  end

endmodule
