"""Top-level CLI driver.

Usage:
    python -m tools.crv.generator --scenario int_hazards --seed 0 --length 200 --out prog.S
"""
from __future__ import annotations
import argparse
import random
from pathlib import Path
from textwrap import dedent

from .scenarios import get_scenario, all_scenarios
from .regfile import GPState, FPState


_HEADER_TEMPLATE = dedent("""\
    # Auto-generated by tools/crv/generator.py
    # scenario={scenario} seed={seed} length={length}
    # Re-run: make run-s5-crv_{scenario}_{seed}

    .section .text
    .global main
    main:
        addi    sp, sp, -16
        sd      ra, 0(sp)
""")

_FOOTER = dedent("""\
        ld      ra, 0(sp)
        addi    sp, sp, 16
        li      a0, 0           # CRV programs always pass at the asm level;
                                # divergence is detected by trace_diff.py.
        ret
""")


def generate_program(scenario: str, seed: int, length: int, out: Path) -> None:
    """Generate one assembly program and write it to `out`."""
    rng = random.Random(seed)
    gp = GPState()
    fp = FPState()
    fn = get_scenario(scenario)
    body = fn(rng, gp, fp, length)

    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write(_HEADER_TEMPLATE.format(scenario=scenario, seed=seed, length=length))
        for instr in body:
            if instr.mnemonic == "":
                # Literal line (e.g. a label) — used by later scenarios.
                f.write(f"{instr.operands[0]}\n")
            else:
                f.write(f"        {instr.to_asm()}\n")
        f.write(_FOOTER)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--scenario", required=True, choices=all_scenarios())
    p.add_argument("--seed", type=int, required=True)
    p.add_argument("--length", type=int, default=200)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()
    generate_program(args.scenario, args.seed, args.length, args.out)


if __name__ == "__main__":
    main()
